name: "Cleanup Kluster"
description: "Destroy a kluster"
inputs:
  token:
    description: "The kubeception token to use"
    required: true
  github-sha:
    description: "The sha of the PR, used for naming the kluster"
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: "Destroy cluster"
      shell: bash
      env:
        DEV_AMBASSADOR_AGENT_KUBECEPTION_TOKEN: ${{ inputs.token }}
      run: |
        # We don't allow the destroy to fail the build; if the kluster couldn't be destroyed now, it'll just be cleaned up when it times out
        go run ./build-aux/kubeception destroy "a8r-agent-ci-${{ inputs.github-sha }}" || true
