{{ $adminNS:="ambassador" }}
{{ if .Values.edgstack }}
{{ if .Values.edgstack.namespace }}
{{ if .Values.edgestack.agent.namespace }}
{{ $adminNS = .Values.edgestack.agent.namespace }}
{{ end }}
{{ end }}
{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-admin-watcher
  namespace: {{ $adminNS }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [ "services" ]
  verbs: [ "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-admin-watcher
  namespace: {{ $adminNS }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ambassador-agent.fullname" . }}-admin-watcher
subjects:
- kind: ServiceAccount
  name: {{ include "ambassador-agent.fullname" . }}
  namespace: {{ include "ambassador-agent.namespace" . }}