{{- if (not .Values.rbac.namespaces) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.getambassador.io/role-group: {{ include "ambassador-agent.rbacName" . }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-pods
  labels:
    rbac.getambassador.io/role-group: {{ include "ambassador-agent.rbacName" . }}
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [ "pods"]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-deployments
  labels:
    rbac.getambassador.io/role-group: {{ include "ambassador-agent.rbacName" . }}
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps", "extensions"]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-endpoints
  labels:
    rbac.getambassador.io/role-group: {{ include "ambassador-agent.rbacName" . }}
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [ "endpoints", "services" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-default-ns
  labels:
    rbac.getambassador.io/role-group: {{ include "ambassador-agent.rbacName" . }}
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [ "namespaces" ]
  resourceNames: ["{{ include "ambassador-agent.namespace" . }}"]
  verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-ingresses
  labels:
    rbac.getambassador.io/role-group: {{ include "ambassador-agent.rbacName" . }}
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: ["networking.k8s.io", "extensions"]
  resources: [ "ingresses" ]
  verbs: [ "get", "list", "watch" ]
{{- if .Values.rbac.argo }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-rollouts
  labels:
    rbac.getambassador.io/role-group: {{ include "ambassador-agent.rbacName" . }}
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: ["argoproj.io"]
  resources: [ "rollouts", "rollouts/status" ]
  verbs: [ "get", "list", "watch", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-applications
  labels:
    rbac.getambassador.io/role-group: {{ include "ambassador-agent.rbacName" . }}
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: ["argoproj.io"]
  resources: [ "applications" ]
  verbs: [ "get", "list", "watch" ]
{{- end }}
{{- end -}}
