{{- if (not .Values.rbac.namespaces) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ambassador-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ambassador-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ambassador-agent.fullname" . }}
  namespace: {{ include "ambassador-agent.namespace" . }}
{{- end -}}
