apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-config
  namespace: {{ include "ambassador-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ambassador-agent.fullname" . }}-config
subjects:
- kind: ServiceAccount
  name: {{ include "ambassador-agent.fullname" . }}
  namespace: {{ include "ambassador-agent.namespace" . }}
{{ $root:=. }}
{{ $argo:=.Values.rbac.argo }}
{{ if .Values.rbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ambassador-agent.fullname" $root }}-get-{{ include "ambassador-agent.namespace" . }}
  namespace: {{ include "ambassador-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" $root }}
    {{- include "ambassador-agent.labels" $root | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ambassador-agent.fullname" $root }}-get-{{ include "ambassador-agent.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ambassador-agent.fullname" $root }}
  namespace: {{ include "ambassador-agent.namespace" $root }}
{{- end -}}

{{ range .Values.rbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ambassador-agent.fullname" $root }}
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" $root }}
    {{- include "ambassador-agent.labels" $root | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ambassador-agent.fullname" $root }}
subjects:
- kind: ServiceAccount
  name: {{ include "ambassador-agent.fullname" $root }}
  namespace: {{ include "ambassador-agent.namespace" $root }}
{{ if $argo }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ambassador-agent.fullname" $root }}-argo
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" $root }}
    {{- include "ambassador-agent.labels" $root | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ambassador-agent.fullname" $root }}-argo
subjects:
- kind: ServiceAccount
  name: {{ include "ambassador-agent.fullname" $root }}
  namespace: {{ include "ambassador-agent.namespace" $root }}
{{ end }}
{{ end }}
