apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-config
  namespace: {{ include "ambassador-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [ "configmaps" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [""]
  resources: [ "secrets"]
  verbs: [ "get", "create", "delete", "patch", "watch"]