apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-config
  namespace: {{ include "ambassador-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [ "configmaps" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [""]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "create", "delete", "patch", "watch" ]
{{ $root:=. }}
{{ $argo:=.Values.rbac.argo }}
{{- if .Values.rbac.namespaces -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-get-{{ include "ambassador-agent.namespace" . }}
  namespace: {{ include "ambassador-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [ "namespaces" ]
  resourceNames: ["{{ include "ambassador-agent.namespace" .  }}"]
  verbs: [ "get" ]
{{- end -}}
{{ range .Values.rbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ambassador-agent.fullname" $root }}
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" $root }}
    {{- include "ambassador-agent.labels" $root | nindent 4 }}
rules:
- apiGroups: 
    - ""
    - "apps"
    - "extensions"
    {{ if $argo }}
    - "argoproj.io"
    {{ end }}
  resources:
    - "ingresses"
    - "services"
    - "pods"
    - "deployments"
    - "endpoints"
    - "configmaps"
    {{ if $argo }}
    - "applications"
    {{ end }}
  verbs: [ "get", "list", "watch" ]
{{ if $argo }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ambassador-agent.fullname" $root }}-argo
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" $root }}
    {{- include "ambassador-agent.labels" $root | nindent 4 }}
rules:
- apiGroups: [ "argoproj.io" ]
  resources: [ "rollouts", "rollouts/status" ]
  verbs: [ "get", "list", "watch", "patch" ]
{{ end }}
{{ end }}
