{{ if .Values.cloudConnectToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ambassador-agent.fullname" . }}-cloud-token
  namespace: {{ include "ambassador-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}-cloud-token
    {{- include "ambassador-agent.labels" . | nindent 4 }}
type: Opaque
data:
  CLOUD_CONNECT_TOKEN: {{ .Values.cloudConnectToken }}
{{ end }}