name: "Publish Ambassador-Agent Helm Chart"
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Build and Publish
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_BUCKET=${{ secrets.AWS_BUCKET }}
        export BUCKET_DIR=${{ secrets.BUCKET_DIR }}
        ./packaging/push_chart.sh

