name: "Publish Ambassador-Agent Helm Chart"
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Build and Publish
      run: |
        pip3 install awscli
        export A8R_AGENT_VERSION=${GITHUB_REF#refs/*/v}
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        [ "$A8R_AGENT_VERSION" != "*-*" ] && export BUCKET_DIR=charts
        ./packaging/push_chart.sh

